[package]
name = "guinix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam = "0.7.0"
slint = "0.3.4"

[build-dependencies]
slint-build = "0.3.4"
